apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cloudstudents
  name: deployment-course-vafiya

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app-course-vafiya
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-course-vafiya
    spec:
      containers:
        - name: app-course-vafiya
          image: 991524241826.dkr.ecr.ap-south-2.amazonaws.com/cloudstudents/vafiya-course:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000   # ✅ FIXED

---
apiVersion: v1
kind: Service
metadata:
  namespace: cloudstudents
  name: service-course-vafiya

spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: app-course-vafiya
  ports:
    - name: http                 # ✅ REQUIRED (fixes pipeline error)
      port: 80                  # ✅ FIXED
      targetPort: 3000          # ✅ FIXED

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: cloudstudents
  name: ingress-course-vafiya
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /   # ✅ important

spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-course-vafiya
                port:
                  number: 80   # ✅ FIXED